In [1]:
import pandas as pd
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_colwidth', 20)

In [2]:
problem_csv = pd.read_csv("problem_metadata.csv")
problem_csv # number of nonzero in hessian 
# row vector column vector and value vector of nonzero values coo
# poor upper bound on hessian sparsity 
# nnzh 
problem_csv.describe()
# ignore nnzh for now not a constant 
# sent csv, run stats boxplots 
problem_csv["time_grad"].isna().sum()

np.int64(10)

In [3]:
solver_csv = pd.read_csv("solver_runtimes.csv")
solver_csv.sort_values(by=["name","nvar", "problem"])
solver_csv["nvar"].value_counts()

nvar
100       6604
1000      6016
10000     4685
1         2800
100000    2681
3         1612
2         1500
4         1300
99        1200
999       1200
9999      1104
8         1100
6          500
500000     416
7          300
961        300
5          204
9997       100
31         100
91         100
988        100
11         100
9          100
99999       48
499998      48
99856       12
499849      12
499993       4
99996        4
499999       1
Name: count, dtype: int64

In [10]:
df = pd.read_csv("./datasets/solver_runtimes.csv")
df.columns

Index(['nvmops', 'objective', 'eval_duration', 'extract_duration',
       'stats_elapsed_time', 'name', 'dual_feas', 'status', 'timed_bytes',
       'timed_time', 'timed_gctime', 'nlp_warmup_time', 'mem', 'neval_grad',
       'iter', 'source', 'nvar', 'problem', 'neval_obj', 'timestamp', 'error'],
      dtype='str')

In [18]:
df["neval_obj"].isna().sum()

np.int64(3109)

In [28]:
df2 = pd.read_csv("problem_metadata.csv")
df2.isna()

,vector_type,extract_duration,highest_degree (ExprTree),nln_nnzj,adbackend_hessian_backend_type,minimize,count_plus_minus,alloc_obj,jtprod_available,has_equalities,...,hprod_available,jtprod_residual_available,alloc_grad,inequality_constrained,time_hess,lin_nnzj,nnzh,timestamp,adbackend_hprod_backend_type,error_type
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
287,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
288,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
289,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
290,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True

In [29]:
final_clean = pd.read_csv("final.csv")
# final_clean[final_clean["name_x"] == final_clean["name_y"]]
# final_clean[["name_x", "name_y"]]
final_clean["error_type"].isna().count()
final_clean

,nvmops,objective,eval_duration_x,extract_duration_x,stats_elapsed_time,name,dual_feas,status,nlp_warmup_time,mem,...,hprod_available,jtprod_residual_available,alloc_grad,inequality_constrained,time_hess,lin_nnzj,nnzh,timestamp_y,adbackend_hprod_backend_type,error_type
0,78.0,1.0,0.751497,0.011845,0.010660,dixmaane,0.000002,first_order,0.690098,1,...,True,NaN,31030832.0,False,NaN,0.0,4950.0,2026-01-31 17:27:51.312,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
1,68.0,1.0,0.751497,0.020418,0.009274,dixmaane,0.000003,first_order,0.690098,2,...,True,NaN,31030832.0,False,NaN,0.0,4950.0,2026-01-31 17:27:51.312,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
2,64.0,1.0,0.751497,0.020405,0.009258,dixmaane,0.000002,first_order,0.690098,3,...,True,NaN,31030832.0,False,NaN,0.0,4950.0,2026-01-31 17:27:51.312,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
3,65.0,1.0,0.751497,0.020353,0.009199,dixmaane,0.000002,first_order,0.690098,4,...,True,NaN,31030832.0,False,NaN,0.0,4950.0,2026-01-31 17:27:51.312,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
4,62.0,1.0,0.751497,0.019437,0.008287,dixmaane,0.000003,first_order,0.690098,5,...,True,NaN,31030832.0,False,NaN,0.0,4950.0,2026-01-31 17:27:51.312,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19617,18.0,-29994.0,0.268935,12.757359,12.754057,schmvett,0.000002,first_order,0.849655,96,...,True,NaN,996516600.0,False,NaN,0.0,50005000.0,2026-01-25 16:40:24.229,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
19618,18.0,-29994.0,0.268935,12.772766,12.760109,schmvett,0.000002,first_order,0.849655,97,...,True,NaN,996516600.0,False,NaN,0.0,50005000.0,2026-01-25 16:40:24.229,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
19619,18.0,-29994.0,0.268935,12.781497,12.758304,schmvett,0.000002,first_order,0.849655,98,...,True,NaN,996516600.0,False,NaN,0.0,50005000.0,2026-01-25 16:40:24.229,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
19620,18.0,-29994.0,0.268935,12.768412,12.755926,schmvett,0.000002,first_order,0.849655,99,...,True,NaN,996516600.0,False,NaN,0.0,50005000.0,2026-01-25 16:40:24.229,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN
19621,18.0,-29994.0,0.268935,12.760122,12.756687,schmvett,0.000002,first_order,0.849655,100,...,True,NaN,996516600.0,False,NaN,0.0,50005000.0,2026-01-25 16:40:24.229,ADNLPModels.ForwardDiffADHvprod{ForwardDiff.Ta...,NaN